---
# file: roles/php/tasks/main.yml
- name: install php
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-devel
    - php-mbstring
    - php-mysql
    - php-mcrypt
    - php-pdo
    - php-pear
  notify:
    - restart httpd
