---
# file: provisioning/local.yml
- name: LAMP-Playbook   # タスク名
  hosts: local          # 対象ホスト
  sudo: yes             # sudoするか
  roles:                # 実際のタスクを記述しているディレクトリ
    - ssh-iptables
    - yum-upgrade
    - yum-update
    - httpd
    - user
    - php
    # - mysql
  vars_prompt:
    - name: "dbpassword"
      prompt: "Please enter MySQL user password"
      default: "hoge"
  tags:                 # タスクをタグ付け
    - httpd
    - user
    - php
    # - mysql
